name: React-expo-CI-CD
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  setting-up:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
        
    - name: install expo
      run: npm install expo

    - name: install expo dependencies
      run: npx expo install react-dom react-native-web @expo/webpack-config

    - name: Prebuild ANDROID expo project 
      run: npx expo prebuild --platform android

###########turtle cli##############
    - name: Install Turtle CLI
      run: npm install -g turtle-cli
    
    - name: Setup Android Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: |
        echo $KEYSTORE_BASE64 | base64 --decode > ./my-release-key.keystore

    - name: aws s3 env
      run: |
           aws s3 cp ./app.json s3://moghany-vprofile-kops-state/react-cicd-apk/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: 'moghany-vprofile-kops-state'

    - name: setup & run local server
      run: |
           npm install http-server
           
    - name: Build APK with turtle cli
      run: |
        turtle build:android \
          --keystore-path ./my-release-key.keystore \
          --keystore-alias $KEY_ALIAS \
          --keystore-password $KEYSTORE_PASSWORD \
          --type apk \
          --allow-non-https-public-url \
          --public-url http://127.0.0.1:8000
          # -o .

######################      
    # # Deploy to S3
    # - name: Deploy to S3
    #   run: |
    #     aws s3 cp path/to/generated/apk/ s3://moghany-vprofile-kops-state/react-cicd-apk/ --recursive
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    #     AWS_REGION: 'us-east-1'

    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-react-expo-cicd-files
    #     path: my-cicd-files

    #you can also use these flags in the following compile cmd --variant debug or --variant release
#    - name: Build for android
#      run: npx expo run:ios --no-build-cache
